apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acmeServer }}
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecret }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - kind: Gateway
                name: {{ .Values.clusterIssuer.gateway.name }}
                # namespace: {{ .Values.clusterIssuer.gateway.namespace }}