apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  # namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "go-app-gateway-api.name" . }}
  {{ include "go-app-gateway-api.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "go-app-gateway-api.name" . }}
  {{ include "go-app-gateway-api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}