apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-654537853-xyz
  namespace: nginx-gateway
spec:
  secretName: argo-654537853-xyz-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - argo.654537853.xyz