apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-homecluster-io
  namespace: platform
spec:
  secretName: argo-homecluster-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argo.homecluster.io