apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homecluster-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx

  listeners:
  # HTTP listener (wildcard)
  # - name: http
  #   hostname: "*.654537853.xyz"
  #   port: 80
  #   protocol: HTTP
  #   allowedRoutes:
  #     namespaces:
  #       from: All
  # HTTP listener for ArgoCD
  - name: argo-http
    port: 80
    protocol: HTTP
    hostname: "argo.654537853.xyz"

  # HTTPS listener for ArgoCD
  - name: https-argo
    hostname: "argo.654537853.xyz"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: argo-654537853-xyz-tls  # this secret will be created by cert-manager
          kind: Secret
          group: ""

  # HTTPS listener for App1
  # - name: https-goapp
  #   hostname: "go-app-gateway-api.654537853.xyz"
  #   port: 443
  #   protocol: HTTPS
  #   allowedRoutes:
  #     namespaces:
  #       from: All
  #   tls:
  #     mode: Terminate
  #     certificateRefs:
  #       - name: go-app-gateway-api-654537853-xyz-tls