apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-creds-access
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["git-creds"]
    verbs: ["get"]