apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.clusterIssuer }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
{{- range .Values.gateway.listeners }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    hostname: "{{ .hostname }}"
    {{- if .allowedRoutes }}
    allowedRoutes:
      namespaces:
        from: {{ .allowedRoutes.namespaces.from }}
    {{- end }}
    {{- if .tls }}
    tls:
      mode: {{ .tls.mode }}
      certificateRefs:
      {{- range .tls.certificateRefs }}
      - name: {{ .name }}
        kind: {{ .kind }}
        group: "{{ .group }}"
      {{- end }}
    {{- end }}
{{- end }}