apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}-route
spec:
  parentRefs:
  - name: homecluster-gateway
    namespace: nginx-gateway
  hostnames:
  - "go-app-gateway-api.654537853.xyz"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Chart.Name }}-service
      port: {{ .Values.service.containerPort }}