apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-gateway-api
  namespace: argocd  # This is the ArgoCD namespace, not the target namespace
spec:
  project: go-apps
  source:
    repoURL: https://github.com/spoved-aws/devops-projects.git
    targetRevision: feature/go-app-gateway-api
    path: charts/go-ks-app-arm  # Path to the Helm chart

  destination:
    server: https://kubernetes.default.svc
    namespace: go-app-gateway-api       # This is the namespace where resources will be deployed
 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true