apiVersion: v1
kind: Service
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}
  labels:
    {{- include "two-tier-flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appService.type }}
  ports:
    - port: {{ .Values.appService.containerPort }}
      targetPort: {{ .Values.appService.targetPort }}
  selector:
    {{- include "two-tier-flask-app.selectorLabels" . | nindent 4 }}
