apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "two-tier-flask-app.name" . }}-mysql
  labels:
    {{- include "two-tier-flask-app.labels" . | nindent 4 }}-mysql
spec:
  serviceName: {{ include "two-tier-flask-app.name" . }}-mysql
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      {{- include "two-tier-flask-app.selectorLabels" . | nindent 6 }}-mysql
  template:
    metadata:
      labels:
        {{- include "two-tier-flask-app.selectorLabels" . | nindent 8 }}-mysql
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -p{{ .Values.mysql.rootPassword }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: {{ .Values.volumeMounts.name }}
          emptyDir: {}