apiVersion: v1
kind: Service
metadata:
  name: {{ include "two-tier-flask-app.name" . }}-mysql
  labels:
    {{- include "two-tier-flask-app.selectorLabels.mysql" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.dbService.containerPort }}
      targetPort: {{ .Values.dbService.containerPort }}
      name: {{ .Values.dbService.name }}
  selector:
    {{- include "two-tier-flask-app.selectorLabels.mysql" . | nindent 4 }}