apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: two-tier-flask-updater   # Name of this ImageUpdater CR
  namespace: argocd
spec:
  namespace: argocd               # Namespace where your Applications live
  applicationRefs:
    - namePattern: "two-tier-flask-app"  # Matches your Application name
      images:
        - alias: "two-tier-flask-app"
          imageName: "kanukhosla10/two-tier-flask-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
  writeBackConfig:
    method: "git:secret:argocd-image-updater/git-creds"
    gitConfig:
      repository: "git@github.com:spoved-aws/devops-projects.git"
      branch: "feature/two-tier-flask-app"
      writeBackTarget: "helmvalues:apps/two-tier-flask-app/charts/values.yaml"